### ISSUE TITLE
[Feature Request] Log deleted messages

### ISSUE THREAD

**Issue by timeakesmarky** [SpriteOvO/Telegram-Anti-Revoke#1]
Thanks for the fantastic tool. Really appreciate it. :)
The deleted messages are gone after restarting telegram desktop app.
Can they be logged somehow to a text file with contact name and deleted message with timestamp?

**Comment by SpriteOvO** [comment]
Sorry to reply to you so late.

Thank you for your request, I think it will be implemented in a future version.
At that time, a settings window will pop up when using this plugin for the first time.
There you can enable the features you want.

**Comment by timeakesmarky** [comment]
Wow, amazing. Thank you so much. :)
Sure, no problem. ^^

A query. Some people are able to see deleted messages on telegram android. How are they doing this? Do you know? Someone said it can be done with Telegram X but I don't see any way.

**Comment by SpriteOvO** [comment]
> A query. Some people are able to see deleted messages on telegram android. How are they doing this? Do you know? Someone said it can be done with Telegram X but I don't see any way.

I once asked the administrator of a group.
He told me that the administrator has the right to view messages deleted by members and is officially allowed.
But I'm not sure.

**Comment by SpriteOvO** [comment]
> A query. Some people are able to see deleted messages on telegram android. How are they doing this? Do you know? Someone said it can be done with Telegram X but I don't see any way.

Group owners and administrators can view messages deleted by members in Manage group-> Recent actions.

**Comment by SpriteOvO** [comment]
> A query. Some people are able to see deleted messages on telegram android. How are they doing this? Do you know? Someone said it can be done with Telegram X but I don't see any way.

Group owner and administrators can view messages deleted by members in Manage group-> Recent actions.

**Comment by SpriteOvO** [comment]
> A query. Some people are able to see deleted messages on telegram android. How are they doing this? Do you know? Someone said it can be done with Telegram X but I don't see any way.

Group owner and administrators can view messages deleted by members in Manage group -> Recent actions.

**Comment by timeakesmarky** [comment]
> Group owner and administrators can view messages deleted by members in Manage group -> Recent actions.

Yeah but normal individual people did that in normal chats. They didn't tell me how.

**Comment by timeakesmarky** [comment]
Hey! This feature is really needed because I can't know which messages were deleted. So, these months, only new deleted messages could be known, rarely. And the "deleted" text can be overlooked, can it be lighter and more visible to the eye? Thanks!

**Comment by SpriteOvO** [comment]
I tried it.
Due to the design of Telegram, only the revoke message event of the currently opened channel can get the content.
So other revoke message events cannot get the content. It also means that they cannot be recorded.

> can it be lighter and more visible to the eye?

Highlight revoke message? This requires reversing part of the Telegram gui code and making future updates more cumbersome.

**Comment by timeakesmarky** [comment]
Oh, isn't there any possible way to record it? Like logging or forwarding to saved messages or any other method.

**Comment by SpriteOvO** [comment]
If you want to save group messages, you can do it through the official robot API.
Monitor each message and save it to your own server.
This requires you to have access to add a bot and allow the bot to read group messages.

If you want to save contact messages, there is probably no way. :(

**Comment by timeakesmarky** [comment]
Oh, pity. :(
Thank you for trying! :)
