### ISSUE TITLE
程序运行是否有dlke.exe程序产生

### ISSUE THREAD

**Issue by liangpu597** [SpriteOvO/Telegram-Anti-Revoke#10]
本地系统win10, 发现每次启动telegram后，会有dlke.exe这个程序自动生成。删除后，再次启动telegram依然会自动生成，请问这个dlke.exe程序是否是有补丁文件产生的？
谢谢！

**Comment by SpriteOvO** [comment]
该插件并不会生成 dlke.exe 文件，您是否使用 Telegram 官方版（从 telegram.org 下载的）？

**Comment by liangpu597** [comment]
@SpriteOvO 是从官方下载的，可以自动接收到更新。我又试了几遍，一打开Telegram，就会自动生成dlke.exe

**Comment by liangpu597** [comment]
然后我又试了下，把version.dll这个文件删除后，打开telegram ,就不会自动生成dlke.exe这个文件了

**Comment by SpriteOvO** [comment]
可以麻烦您打包上传一下 Telegram.exe 、version.dll 和 dlke.exe 这3个文件吗

**Comment by SpriteOvO** [comment]
如果删除 version.dll 插件文件，运行 Telegram.exe 依旧会生成 dlke.exe 文件吗？

**Comment by liangpu597** [comment]
@SpriteOvO  我删除插件文件，运行telegram 发现 还是会生成dlke ，该死的。可能是中毒了~~~~

**Comment by SpriteOvO** [comment]
> @SpriteOvO 我删除插件文件，运行telegram 发现 还是会生成dlke ，该死的。可能是中毒了~~~~

建议你先将 dlke.exe 文件上传到 微步、哈勃 等文件在线分析网站，查看该文件的行为。
然后用杀毒软件进行全盘杀毒，或者直接重装系统。
