### ISSUE TITLE
[Feature Request] Add support for showing edit history

### ISSUE THREAD

**Issue by runapp** [SpriteOvO/Telegram-Anti-Revoke#11]
Thank you for the plugin. Currently one can bypass the current anti-invoke plugin by always editing the message to empty and then delete it. (Only for text) Is there any plan to add an option to keep edit history?

**Comment by SpriteOvO** [comment]
Due to the design of Telegram, only revoked/edited message events in the currently open channel/group can fetch content, while revoked/edited message events in the unopened channel/group cannot.

This means that the content of the message cannot be recorded.

**Comment by SpriteOvO** [comment]
And recording each message will take up CPU and memory/hard disk space and may result in a user privacy breach.

So there are no plans to add this feature at this time.
Thank you for submitting!

**Comment by SpriteOvO** [comment]
Recording each message will take up CPU and memory/hard disk space and may accidentally compromise user privacy (meaning that the message content may be stolen by other software).

So there are no plans to add this feature at this time.
Thank you for submitting!

**Comment by runapp** [comment]
I see. I do understand that telegram won't load all messages of inactive chats. Anyway adding that function as an opt-in would be a great dual-backup for me. However, I'm too naive on hooking that won't be able to implement it myself.
Should I keep this issue open and wait for some kind man, or close it?

**Comment by SpriteOvO** [comment]
> I see. I do understand that telegram won't load all messages of inactive chats. Anyway adding that function as an opt-in would be a great dual-backup for me. However, I'm too naive on hooking that won't be able to implement it myself.

The function for message editing should be this.

https://github.com/telegramdesktop/tdesktop/blob/f76e094e98dd678158c6f97dcc690548919cbe16/Telegram/SourceFiles/data/data_session.h#L388

I'm not sure, but good luck with that!

> Should I keep this issue open and wait for some kind man, or close it?

Just keep it open, someone may have the same problem in the future.
If it needs to be closed, I will do it.

**Comment by lupohan44** [comment]
Is it possible to get previous message instead of caching everymessage from this API?
https://github.com/telegramdesktop/tdesktop/blob/75fc88d679c27316af54af16dfa67103fded7dd5/Telegram/SourceFiles/data/data_session.cpp#L1798-L1813

**Comment by SpriteOvO** [comment]
> Is it possible to get previous message instead of caching everymessage from this API? https://github.com/telegramdesktop/tdesktop/blob/75fc88d679c27316af54af16dfa67103fded7dd5/Telegram/SourceFiles/data/data_session.cpp#L1798-L1813

I don't think so, it should be impossible for any API to return the previous content for messages that have been edited.
