### ISSUE TITLE
[Question] How to Use?

### ISSUE THREAD

**Issue by A-S-K-3** [SpriteOvO/Telegram-Anti-Revoke#12]
Is there any how to use guide available. In usage you said to copy version.dll file to telegram directory. I am not seeing a version.dll file in your repo. Please provide a description of how to use

**Comment by SpriteOvO** [comment]
Download the latest version from the Release page: https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases

**Comment by A-S-K-3** [comment]
Sorry, forgot to check the release tab :| . Thanks for replying
