### ISSUE TITLE
[Bug report] Plugin does not work in v2.1.5

### ISSUE THREAD

**Issue by ProMan987** [SpriteOvO/Telegram-Anti-Revoke#13]
### Describe the bug
When Opening  up telegram it shows an error message 
Link: https://prnt.sc/sg7y7b

### Steps to reproduce
1. Update To Telegram v 2.1.5
2. Restart or Start Telegram after update

### Expected behaviour
it should just open normal like every time and the plugin works

### Actual behaviour
When Opening  up telegram it shows an error message 
Link: https://prnt.sc/sg7y7b

### Configuration
* Operating system: Windows 10 Pro x64
* Version of Telegram: 2.1.5

<details><summary><b>Logs</b></summary>
Insert ArLog.txt here. (if necessary)<br>
It's in the same directory as the avrt.dll file.
</details>

**Comment by SpriteOvO** [comment]
请尝试升级 TG 到 2.1.6 版本，插件应该可以正常工作。

**Comment by SpriteOvO** [comment]
Is the problem solved?

**Comment by ProMan987** [comment]
Yes sir after updating the problem was solved thanks !
