### ISSUE TITLE
Deleted Messages Disappear

### ISSUE THREAD

**Issue by ProMan987** [SpriteOvO/Telegram-Anti-Revoke#14]
### Describe the bug
When i click on someone's reply and the telegram go to that message up there and then i go back to the chat the deleted messages Disappear.

### Steps to reproduce
1. go to any group chat 
2. click on someone's reply that's up in the chat view 
3. click the arrow to go to the recent/new messages 

### Expected behaviour
the deleted messages should not be deleted when i move through users replies.

### Actual behaviour
deleted messages disappear.

### Configuration
* Operating system: Windows 10 Pro x64
* Version of Telegram: 2.1.6

<details><summary><b>Logs</b></summary>
Insert ArLog.txt here. (if necessary)<br>
It's in the same directory as the version.dll file.
</details>

**Comment by SpriteOvO** [comment]
A message that jumps to long ago will cause Telegram to directly clear all messages from the current memory and then download messages near the jump location.

That's why the plugin prevents messages from being deleted but they may still disappear after a while.

This problem may be fixable, but it will cause Telegram to use more memory, require the plugin to do more patches to Telegram, and make future updates more troublesome.

I don't think it's worth it, so there are no plans to fix it for now.
Thank you for the report!

**Comment by ProMan987** [comment]
> A message that jumps to long ago will cause Telegram to directly clear all messages from the current memory and then download messages near the jump location.
> 
> That's why the plugin prevents messages from being deleted but they may still disappear after a while.
> 
> This problem may be fixable, but it will cause Telegram to use more memory, require the plugin to do more patches to Telegram, and make future updates more troublesome.
> 
> I don't think it's worth it, so there are no plans to fix it for now.
> Thank you for the report!

can you create something like deleted messages log in a file ? or can i forward deleted messages to saved messages chat ? it would be very helpful to take a look at unseen deleted messages if you can make the plugin log them in a file with chat id and user first name ..etc  because sometimes the telegram updates or the pc shuts down so i lose all the deleted messages on all chats 

note: also some chats like groups i really don't know how to make it automatically download the images and files before it gets deleted because some videos or images are marked as deleted but i can't view them or they are deleted from the telegram server ?

**Comment by SpriteOvO** [comment]
> can you create something like deleted messages log in a file ? or can i forward deleted messages to saved messages chat ? it would be very helpful to take a look at unseen deleted messages if you can make the plugin log them in a file with chat id and user first name ..etc because sometimes the telegram updates or the pc shuts down so i lose all the deleted messages on all chats

#1 

> note: also some chats like groups i really don't know how to make it automatically download the images and files before it gets deleted because some videos or images are marked as deleted but i can't view them or they are deleted from the telegram server ?

Telegram automatically downloads images or videos only in the currently opened group/channel.
They may have been deleted on the Telegram server before you downloaded them.

**Comment by timeakesmarky** [comment]
If the whole chat is deleted, only the chat that is loaded on telegram is available to copy, not the past messages that loads when you scroll up. Is there a way to keep all messages?

**Comment by SpriteOvO** [comment]
> If the whole chat is deleted, only the chat that is loaded on telegram is available to copy, not the past messages that loads when you scroll up. Is there a way to keep all messages?

No way
