### ISSUE TITLE
[Question]  The way to compile Telegram

### ISSUE THREAD

**Issue by plummm** [SpriteOvO/Telegram-Anti-Revoke#15]
Hi Sprite,
I found a lot of difficulties when I am reversing Telegram without a symbol file. So I try to compile it on local (follow the official document step by step)but encounter errors.
From your project’s description, I guess there is some sort of tricks, could you give me any suggestions about how to compile it correctly.

**Comment by SpriteOvO** [comment]
I wrote a [Telegram compilation guide](https://blog.csdn.net/u012088909/article/details/104486027) and hope it helps you.

**Comment by plummm** [comment]
> I wrote a [Telegram compilation guide](https://blog.csdn.net/u012088909/article/details/104486027) and hope it helps you.

This is very helpful, thank you so much!
