### ISSUE TITLE
[Bug report] 插件在 Telegram v2.1.14 beta 版本中失效

### ISSUE THREAD

**Issue by zhou2002** [SpriteOvO/Telegram-Anti-Revoke#17]
Windows新版TG的Beta版现已经支持多账号登录,版本号2.1.14Beta,非Beta版现在还是可以用的,这个Beta版开始就失效了.如果您有空的话麻烦您更新一下哟~

**Comment by zhou2002** [comment]
![image](https://user-images.githubusercontent.com/38722335/86067047-6deff000-baa6-11ea-843b-bdde946755c9.png)
打开TG还弹窗了这个

**Comment by SpriteOvO** [comment]
[v0.2.2 新版本](https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases/tag/0.2.2) 已修复

**Comment by zhou2002** [comment]
Thx~

**Comment by zhou2002** [comment]
> Windows 新版 TG 的 Beta 版现已经支持多账号登录，版本号 2.1.14Beta, 非 Beta 版现在还是可以用的，这个 Beta 版开始就失效了。如果您有空的话麻烦您更新一下哟～
