### ISSUE TITLE
[Bug report] 升级到 2.1.7 beta 提示 SearchSigns() Failed

### ISSUE THREAD

**Issue by KLDGodY** [SpriteOvO/Telegram-Anti-Revoke#18]
如下图 ==
重启了还是不行

![NxFtLq.png](https://s1.ax1x.com/2020/07/04/NxFtLq.png)

**Comment by SpriteOvO** [comment]
请尝试 [v0.2.2 新版本](https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases/tag/0.2.2)
由于 Tg 更新的是 beta 版本，所以插件暂时没有强制推送更新

**Comment by KLDGodY** [comment]
可以了 thanks
