### ISSUE TITLE
[Question] 防撤回插件不起作用

### ISSUE THREAD

**Issue by darklord335349059** [SpriteOvO/Telegram-Anti-Revoke#2]

**Comment by SpriteOvO** [comment]
请检查 Telegram 根目录下是否存在 ArLog.txt 文件。
如果该文件不存在，则是因为劫持 avrt.dll 失败导致。
近期将更新新版本解决该问题。
请持续关注，谢谢！

**Comment by darklord335349059** [comment]
谢谢 大佬回复。刚才看了  我的telegram安装在D盘的D:\Telegram Desktop 下。里面只有一个log.txt文档 ，没有你说的ArLog.txt文件

**Comment by dawn-lc** [comment]
telegram未加载插件
![image](https://user-images.githubusercontent.com/30336566/73192549-261a1500-4164-11ea-8803-c901bd76c393.png)
![image](https://user-images.githubusercontent.com/30336566/73192576-30d4aa00-4164-11ea-91af-dc64c600af1a.png)

**Comment by SpriteOvO** [comment]
@dawn-lc 感谢反馈 已经在写了。

**Comment by SpriteOvO** [comment]
修复这个问题的测试版发布了，没效果的朋友可以去试试。
https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases/tag/0.1.4

测试没问题了，记得回来回复一声。

**Comment by SpriteOvO** [comment]
由于该 issue 长期无人回复，我就先关闭了。
如果有问题请再随时打开该 issue 或新开 issue。

**Comment by darklord335349059** [comment]
已经解决了
