### ISSUE TITLE
请问，安装了插件以后，是不是已撤回的图片，依然不能下载观看？

### ISSUE THREAD

**Issue by sfwsky** [SpriteOvO/Telegram-Anti-Revoke#20]
RT，群里已撤回的图片，显示deleted，不能下载打开

**Comment by SpriteOvO** [comment]
如果图片在被撤回前，没有被 缓存 / 下载 的话，是这样的。
原因很简单，对方撤回后，该图片已经从服务器中删除，你再去请求下载，服务器也找不到。
视频同理。

**Comment by sfwsky** [comment]
tg里设置了自动下载也不行么

**Comment by SpriteOvO** [comment]
TG 有优化的，你设置的自动下载，仅限于你当前打开的群组，没打开的群组不会自动下载。

**Comment by chay0404** [comment]
能不能弄个自动游览啊，有时候做着其它事情它就不会自动游览了(auto scroll)
