### ISSUE TITLE
[Question] 请教下，我拷到根目录，测试了下貌似没生效

### ISSUE THREAD

**Issue by ljhappy026** [SpriteOvO/Telegram-Anti-Revoke#21]
win10系统，拷贝位置：C:\Users\Administrator\AppData\Roaming\Telegram Desktop
测试了下删除，但是没生效，telegram版本2.2

问下，这个dll文件根目录是没有的吧，还有是否我拷错位置了？

**Comment by SpriteOvO** [comment]
你拷贝的目录是 Telegram 缓存目录
根目录是指：桌面 -> Telegram 快捷方式 -> 右键 -> 打开文件所在的位置

**Comment by i35010u** [comment]
我也是这样，而且我桌面右键快捷方式也是那个文件夹

**Comment by SpriteOvO** [comment]
@i35010u 是拷贝了 _version.dll_ 后重启 _Telegram_ 防撤回没效果吗？能否提供一下 _Telegram_ 根目录截图？

**Comment by i35010u** [comment]
![image](https://user-images.githubusercontent.com/60495797/90250190-485c5180-de6e-11ea-82e0-49c01ddae45d.png)

**Comment by SpriteOvO** [comment]
@i35010u _ArLog.txt_ 是插件的日志文件，从你这个截图来看，插件是加载成功了的。
方便的话，可以在手机端登录 Telegram，向自己的收藏夹发送一条消息并撤回，以验证插件有没有起效果。

**Comment by i35010u** [comment]
@SpriteOvO 那我待会找人试试
