### ISSUE TITLE
你好，请问dll注入您是读了那些书籍文档？我也想研究下

### ISSUE THREAD

**Issue by 5m17h** [SpriteOvO/Telegram-Anti-Revoke#22]
我看了你是放了个dll文件进去，请问dll注入您是读了那些书籍文档才设计出这个的？我也想研究下

**Comment by SpriteOvO** [comment]
系统 DLL 文件劫持这个知识是通过破解补丁认识的。
转发导出函数的代码由于过于繁琐，故使用了 AheadLib 工具生成，并根据需要做了修改。
