### ISSUE TITLE
[Question] 删除的信息消失

### ISSUE THREAD

**Issue by Learner-Victor** [SpriteOvO/Telegram-Anti-Revoke#23]
选择历史信息跳转的时候/点击回复的信息（跳转篇幅大时），如果感觉到一个卡的感觉，该群组已删除的信息就会全部消失。

**Comment by Learner-Victor** [comment]
> 选择历史信息替换的时间/点击回复的信息（更改篇幅大时），如果感觉到一个卡的感觉，该类别已删除的信息就会全部消失。

**Comment by SpriteOvO** [comment]
#14
