### ISSUE TITLE
[Question] 消息记录被删除后不可见

### ISSUE THREAD

**Issue by Learner-Victor** [SpriteOvO/Telegram-Anti-Revoke#24]
请问是不是群管理删除的群消息插件不会生效？

**Comment by SpriteOvO** [comment]
不是，不限于是谁删除的

**Comment by Learner-Victor** [comment]
> 不是，不限于是谁删除的

就昨天，好像管理员直接删除所有聊天记录的话，插件不能生效。。直接返回到最初的XXX join the grou。可能是因为那个昨天提的跳转问题吧orz。

**Comment by SpriteOvO** [comment]
是否重启了 TG 呢？如果消息被撤回后重启了 TG，被撤回的消息会全部消失

**Comment by Learner-Victor** [comment]
> 是否重启了 TG 呢？如果消息被撤回后重启了 TG，被撤回的消息会全部消失

没有啊，因为重启tg以及点击跳转信息都会造成撤回信息消失，所以都尽量避免了这些操作，除非telegram闪退，不过并没有闪退今天。

**Comment by SpriteOvO** [comment]
你先试试点击群组聊天框中的日期，然后最初消息，看看能不能跳出之前的消息，这个好像是个 TG 桌面端的 bug，我也遇到过。
另外如果你启动 TG 后没有打开过该群组，就等于本地没缓存过该群的任何一条消息，这种情况消息被撤回应该也是拦截不到的。

**Comment by Learner-Victor** [comment]
> 你先试试点击群组聊天框中的日期，然后点最初消息，看看能不能跳出之前的消息，这个好像是个 TG 桌面端的 bug，我也遇到过。
> 
> 另外如果你启动 TG 后没有打开过该群组，就等于本地没缓存过该群的任何一条消息，这种情况消息被撤回应该也是拦截不到的。

就日期那里可以追溯到入群的时间，但是8/31到入群之间的消息都没了，被清空了，今天一天都开着telegram，也有留意群组内信息，所以是缓存了的，就是群主删除信息后之前显示已删除的信息直接消失，所以我认为可能是跳转的问题。

**Comment by SpriteOvO** [comment]
emmm 也许是吧，有空我再详细研究下

**Comment by Learner-Victor** [comment]
> emmm 也许是吧，有空我再详细研究下

嗯，感谢大佬
