### ISSUE TITLE
[Bug report] 更新后提示bug且无法防撤回

### ISSUE THREAD

**Issue by Paulkm2006** [SpriteOvO/Telegram-Anti-Revoke#26]
### Describe the bug
更新TG Desktop v2.4后启动时跳出如下提示框且防撤回功能失效
![image](https://user-images.githubusercontent.com/20290410/94752968-5f73e600-03bf-11eb-8869-228a15786639.png)

### Steps to reproduce
1. 更新TG desktop至v2.4
2. 启动TG
3. 跳出提示框，点击忽略
4. 无法防撤回

### Expected behaviour
正常启动且防撤回
### Actual behaviour
无法防撤回

### Configuration
* Operating system: Windows Server 2012R2
* Version of Telegram: v2.4

<details><summary><b>Logs</b></summary>

[ArLog.txt](https://github.com/SpriteOvO/Telegram-Anti-Revoke/files/5308877/ArLog.txt)

</details>

**Comment by YoTianmo** [comment]
同样

**Comment by pppwaw** [comment]
应该是 `InitOffsets` 的偏移量出了问题，也就是说tg更新了偏移

**Comment by Vanimes** [comment]
same question

**Comment by Chiyukichan** [comment]
同上

**Comment by pppwaw** [comment]
同样，估计是 `InitOffsets` 出了问题（猜的）

**Comment by SpriteOvO** [comment]
刚醒呢，马上起来更新，急用的朋友可以先用旧版本TG

**Comment by Chiyukichan** [comment]
旧版本TG客户端下载地址：https://telegram-for-desktop.cn.uptodown.com/windows/versions

**Comment by jyeric** [comment]
+1

**Comment by SpriteOvO** [comment]
已更新：https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases/tag/0.2.4
