### ISSUE TITLE
Telegram 2.4.1 使用插件可能导致崩溃

### ISSUE THREAD

**Issue by lbcake** [SpriteOvO/Telegram-Anti-Revoke#27]
新版本2.4.1  我win7 装上对应版本后 tg 总是无缘无故自动退出

**Comment by SpriteOvO** [comment]
请尝试删除插件文件，重启 TG 看看还会不会奔溃。
如果确认是插件的问题可以上传目录下的 Arlog.txt 文件帮助分析。

**Comment by SpriteOvO** [comment]
另外可以升级 TG 到 2.4.1，看看崩溃问题有没有得到改善。

**Comment by Learner-Victor** [comment]
> 另外可以升级 TG 到 2.4.1，看看崩溃问题有没有得到改善。

WIN10也

**Comment by Learner-Victor** [comment]
[2020.10.02-13:56:03] [Warn]  A bad TimeText. Address: [0x237eb198] Content: [?]

**Comment by SpriteOvO** [comment]
我这边挂着调试器看看，但我从早上到现在还没复现出崩溃

**Comment by Learner-Victor** [comment]
> 我这边挂着调试器看看，但我从早上到现在还没复现出崩溃

感觉可能是telegram的问题。。
[2020.10.02 15:05:21] API Warning: real mentions count is greater than received mentions count
[2020.10.02 15:05:34] Assertion Failed! Unexpected: Qt FATAL message was generated! crash_reports.cpp:129

**Comment by SpriteOvO** [comment]
刚刚调试了一下，可能是由于 TG 在 v2.4.1 更新了一个地方导致的，可能会导致消息无法防撤回或直接崩溃。
插件新版本 v0.2.5 已经修复了，可以在[这里](https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases)下载。

**Comment by Learner-Victor** [comment]
> 刚刚调试了一下，可能是由于 TG 在 v2.4.1 更新了一个地方导致的，可能会导致消息无法防撤回或直接崩溃。
> 插件新版本 v0.2.5 已经修复了，可以在[这里](https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases)下载。

好，爱你
