### ISSUE TITLE
[Bug report] 每次打开依旧提示新版本更新

### ISSUE THREAD

**Issue by hjthjthjt** [SpriteOvO/Telegram-Anti-Revoke#28]
### Describe the bug
已安装最新 0.2.4/0.2.5，每次打开 Telegram 时都会提示我在使用 0.1.3，很迷惑……

### Configuration
* Operating system: Windows 10 2004
* Version of Telegram: 2.4.0/2.4.1

![image](https://user-images.githubusercontent.com/3889846/94901747-acdc7a00-04c9-11eb-9766-8b5dc9c6370a.png)
![image](https://user-images.githubusercontent.com/3889846/94901773-bb2a9600-04c9-11eb-85b8-e3beb6a16102.png)
![image](https://user-images.githubusercontent.com/3889846/94901942-03e24f00-04ca-11eb-9fe5-deadc098cd48.png)

**Comment by SpriteOvO** [comment]
请问您确定最新版本已复制到 Telegram 根目录下了吗？
这有些奇怪，因为自插件 v0.2.3 起，如果检测到有新版本发布，会在提示框中显示出新版本的更新内容。
而如图中并没有如此显示，这符合 v0.2.3 版本之前的情况。

**Comment by hjthjthjt** [comment]
是的……我是前段时间才想起这个插件得更新，所以版本跨度比较大
![image](https://user-images.githubusercontent.com/3889846/94902488-d0ec8b00-04ca-11eb-88c6-795bf53d2bce.png)

**Comment by SpriteOvO** [comment]
我注意到您的目录下有 arvt.dll 文件，该文件由于部分用户系统不兼容的缘故已经从 v0.1.4 Beta 版本开始更换为 version.dll。
只需删除 arvt.dll 文件即可。

**Comment by hjthjthjt** [comment]
啊好了，谢谢（
