### ISSUE TITLE
[Feature Request] Cantonese support

### ISSUE THREAD

**Issue by Rongronggg9** [SpriteOvO/Telegram-Anti-Revoke#29]
### Is your feature request related to a problem? Please describe.
Pragmatically speaking, no. 

### Describe the solution you'd like
* The word "deleted" should be replaced by "刪咗" if detected a Cantonese translation applied.
* These are popular Cantonese translations (from https://t.me/localization_hk/498):
```
🇭🇰 香港人口語
tg://setlanguage?lang=hongkonger
適用於：Android／iOS
簡介：模仿香港人講嘢時中英夾雜

🇭🇰 廣東話
tg://setlanguage?lang=cantonese
適用於：Android／iOS／TDesktop
簡介：使用中文用詞嘅廣東話

🇭🇰 港式潮語
tg://setlanguage?lang=hkslang
適用於：Android／iOS
簡介：以廣東話為藍本，改用巴絲、AGGER 等論壇用語

🇭🇰 香港廣東話（18+）
tg://setlanguage?lang=hkcantonese
適用於：Android／iOS
簡介：廣東話為主，內含粗口 🔞
```

### Describe alternatives you've considered
* Actually, these 4 use different translations for "deleted":
    * `cantonese` uses "刪咗".
    * `hkslang` and `hkcantonese` use "剷咗".
    * `hongkonger` uses "delete 咗".

For now only `cantonese` is suitable for Telegram Desktop, so the other three can be temporary ignored.

**Comment by SpriteOvO** [comment]
Done! This feature will be available in the next release. Thank you!

**Comment by SpriteOvO** [comment]
New version released. [v0.2.6](https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases/tag/0.2.6)
