### ISSUE TITLE
tportable.2.0.1,这种的root directory是哪个

### ISSUE THREAD

**Issue by meetinnet** [SpriteOvO/Telegram-Anti-Revoke#30]
是跟Telegram.exe同一个文件夹，还是那个tdata下面，还是不支持这个版本，自发自撤的测试不成功。

**Comment by SpriteOvO** [comment]
插件 version.dll 是要放在和 Telegram.exe 同文件夹内。
我刚测试了，插件最新版本是兼容 TG v2.0.1 的。
在同一设备中，自己删除自己的消息是不会被插件阻止的，可以在手机端上删除消息进行测试。

**Comment by meetinnet** [comment]
收到，多谢，我再试试~

**Comment by meetinnet** [comment]
早晨发现，如果一个群员发了消息之后，退了群或者被踢出群，管理员删除了他的消息，那么也是看不到的，没有任何痕迹。

**Comment by SpriteOvO** [comment]
> 早晨发现，如果一个群员发了消息之后，退了群或者被踢出群，管理员删除了他的消息，那么也是看不到的，没有任何痕迹。

该问题可能类似于 #24
