### ISSUE TITLE
群组消息bot删除消息问题

### ISSUE THREAD

**Issue by aabababb** [SpriteOvO/Telegram-Anti-Revoke#32]
群组有垃圾消息，己经被bot删除了，这种消息也是防撤回，依然能看到了？

**Comment by SpriteOvO** [comment]
是的。
但如果垃圾信息发出来后，客户端还没有收到这条消息就被 BOT 删除了，这种情况是没法防撤回的。

**Comment by aabababb** [comment]
> 
> 
> 是的。
> 但如果垃圾信息发出来后，客户端还没有收到这条消息就被 BOT 删除了，这种情况是没法防撤回的。

-_-!!  不能做个判断么？bot删除的消息，就不要防撤回了。。。

**Comment by SpriteOvO** [comment]
本地是取不到消息是被谁撤回的，所以没法判断。
之前有尝试过，判断如果是 BOT 发的消息就不防撤回，但是暂时没法区分是群组内的 BOT 还是私聊中的 BOT（考虑到 PM BOT），所以还没发布该功能。

**Comment by aabababb** [comment]
还是发布吧，bot的再让自己设置选择是否防撤，个人觉得bot的消息不需要防撤，删就删了。

**Comment by SpriteOvO** [comment]
> 还是发布吧，bot的再让自己设置选择是否防撤，个人觉得bot的消息不需要防撤，删就删了。

“PM BOT” 即 “私聊 BOT” ，加入该功能也就意味着他人通过 “私聊 BOT” 删除的消息无法防撤回。
我觉得该功能目前的弊端大于益处，而且目前没有 GUI 设置框，没有办法让用户轻松改变设置。
所以决定先放入 TODO 列表内，会在完善好该功能后发布，感谢您的反馈！
