### ISSUE TITLE
插件不兼容 TG 2.4.5 新版本

### ISSUE THREAD

**Issue by teolinkiat** [SpriteOvO/Telegram-Anti-Revoke#33]
### Steps to reproduce
1. Tg更新2.4.5了，防撤回插件造成TG无法启动。
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
* Operating system: 
* Version of Telegram: 

<details><summary><b>Logs</b></summary>
Insert ArLog.txt here. (if necessary)<br>
It's in the same directory as the version.dll file.
</details>

**Comment by SpriteOvO** [comment]
我这边暂时没收到 2.4.5 的更新推送。
检查更新提示 2.4.4 是最新版，看了下官方 GitHub 仓库也没有发布 2.4.5 提交和版本。
只能等等再看。
