### ISSUE TITLE
[Question] 插件被windows defender flag成virus了

### ISSUE THREAD

**Issue by peteristik** [SpriteOvO/Telegram-Anti-Revoke#34]
Threat Detected: "Trojan:Win32/Wacatac.DD!ml"

**Comment by SpriteOvO** [comment]
最新版 0.2.6 上传至微步云沙箱的分析结果：[跳转](https://s.threatbook.cn/report/file/db9fdc70f521649319cc92c10d666a98bbd8d4a03fcbe9716a10fc538dfc4363/?env=win7_sp1_enx64_office2013)
由于目前插件没有微软的软件数字签名，其行为可能会造成某些杀毒软件误报。
建议您将插件添加到 Windows defender 或 其他造成误报杀软 的白名单来暂时解决问题。
插件是完全开源的，如实在不放心也可以自行检查源代码并编译使用哦。

**Comment by peteristik** [comment]
感谢回复。谢谢您开发这个插件。
