### ISSUE TITLE
[Question] Are you interested in taking charge of a similar project?

### ISSUE THREAD

**Issue by plummm** [SpriteOvO/Telegram-Anti-Revoke#36]
Hey,
This is a great project. I used to work on a similar [one](https://github.com/plummm/AntiRecall) last year for my class project.
I implemented an anti-revoke tool for WeChat, QQ, and Telegram. The Telegram part was based on your research. That was very helpful.
Since I don't have enough time to maintain this project anymore, and people keep querying for new versions' supports of WeChat and Telegram. I am wondering if you are interested in taking charge of my project? I have notes that may help you maintain the anti-revoke for WeChat and QQ.

Please let me know if you have any concerns.

**Comment by SpriteOvO** [comment]
Thanks for your recognition, but I've also been busy with my other projects and haven't had much free time to maintain a new one, and another reason is that I'm not familiar with C#, so I'm sorry.

**Comment by plummm** [comment]
No problem, I totally understand.
