### ISSUE TITLE
不在线期间无法防撤回

### ISSUE THREAD

**Issue by wangshuaishuaishuai** [SpriteOvO/Telegram-Anti-Revoke#38]
我是win7的系统，用了好几天了感觉确实很强，也发现了几个问题：
1、不登录期间别人发的消息是可以正常撤回的
2、登陆期间有些消息也可以撤回，但会显示“已删除”，这些撤回的图片会呈现模糊状态，就好像没有下载下来一样
3、登录时间长了会报错，必须重新打开软件，但是重新打开就看不到之前被阻止撤回的内容了
目前有这几个问题，希望能引起大佬重视，感谢大佬提供的便利，加油！
![登陆期间撤回的图片](https://user-images.githubusercontent.com/77291861/104899634-1075af00-59b6-11eb-8ee7-3197487ee310.PNG)

**Comment by SpriteOvO** [comment]
1、是的，因为该插件仅适用于缓存到本地消息，并没有能力也没有办法使服务器保留撤回消息。
2、重复 #20。
3、报错是指？有截图吗？

**Comment by wangshuaishuaishuai** [comment]
哇，感谢大佬回复
1、意思是如果别人撤回的快，我们电脑还没缓存就会出现这种情况吗
![image](https://user-images.githubusercontent.com/77291861/104922248-6a39a180-59d5-11eb-8e0e-ef8948bf37bb.png)
2、我下次出现bug给你截图啊，之前以为是我电脑问题

**Comment by SpriteOvO** [comment]
> 1、意思是如果别人撤回的快，我们电脑还没缓存就会出现这种情况吗

是的。

> 2、我下次出现bug给你截图啊，之前以为是我电脑问题

那这个 issue 我先关闭了，下次反馈请新开一个 issue，因为这个 issue 有多个不同的问题。

**Comment by wangshuaishuaishuai** [comment]
大佬有了
![Uploading bug.png…]()

**Comment by wangshuaishuaishuai** [comment]
大佬bug出现了
![bug](https://user-images.githubusercontent.com/77291861/105124726-b5f36480-5b15-11eb-8b51-7f057c0b282e.png)
