### ISSUE TITLE
[Question] Anti-Revoke plugin does not work.

### ISSUE THREAD

**Issue by Greeni662** [SpriteOvO/Telegram-Anti-Revoke#4]
I have packed the file avrt.dll in the main installation directory of Telegram: D:\Telegram Desktop. Still nothing happens. Maybe you can tell me where my error is. I use Windows 10 64bit and Telegram Desktop Version 1.9.9

**Comment by SpriteOvO** [comment]
Please check if the ArLog.txt file exists in the root directory after starting TG.
If the file does not exist, it is because the hijacking of avrt.dll failed.
The error is trying to be fixed. Thank you for your feedback!

**Comment by Greeni662** [comment]
I have checked all over there are only the normal telegram log

**Comment by SpriteOvO** [comment]
A beta version to fix this bug is released, try it.
https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases/tag/0.1.4

If the test is OK, remember to tell me here please.

**Comment by Greeni662** [comment]
Thanks now it works
