### ISSUE TITLE
切换/重新登入账号，重启应用程序会丢失被撤回消息的记录

### ISSUE THREAD

**Issue by moexizer** [SpriteOvO/Telegram-Anti-Revoke#41]
希望能够保留这些内容

**Comment by SpriteOvO** [comment]
TG 现版本支持单端多账号登录，在其中切换账号不会丢失被撤回的消息。
重登账号 和 重启程序 丢失被撤回消息的问题，见 #38。

**Comment by moexizer** [comment]
感谢回复。我尝试在桌面端运行期间切换多账号，被撤回群消息在加载未读新消息过程中发生丢失。
桌面版 2.5.1 。

**Comment by SpriteOvO** [comment]
> 感谢回复。我尝试在桌面端运行期间切换多账号，被撤回群消息在加载未读新消息过程中发生丢失。
> 桌面版 2.5.1 。

未加载（缓存）的消息被撤回，就算不切换账号也没法保留下来
