### ISSUE TITLE
绿色(portable)版无效

### ISSUE THREAD

**Issue by singularity2000** [SpriteOvO/Telegram-Anti-Revoke#43]
晕 不知道介绍中所说的“telegram根目录”在哪里
索性和绿色版telegram放在一起。
运行并测试删除自己发的消息，发现还是整个地消失了
不知是否支持win10绿色版？如果支持该如何解决此问题？

**Comment by SpriteOvO** [comment]
启动 TG 后，检查 TG 根目录有没有创建 ArLog.txt 文件，该文件是插件的日志文件，如果没有的话说明插件没有加载成功。
如果该文件存在，最多需要等半分钟到一分钟左右，这段时间插件会检查更新，所以防撤回功能不会起效。

另外还请检查您使用的 portable 版本是否为 x64 版本，x64 版是 TG 这次 2.5.7 版本更新释出的，插件目前仅兼容 x86 版本，对于兼容 x64 版本的工作正在进行中。

**Comment by singularity2000** [comment]
非常感谢 后来发现插件能正常工作！回复很快很专业，一读就懂。作者是天才。（另外想打听一下安卓端telegram有没有防撤回工具，以及在哪下载）

**Comment by SpriteOvO** [comment]
> 另外想打听一下安卓端telegram有没有防撤回工具，以及在哪下载

暂时没有，相关问题已有讨论，详见 #19
