### ISSUE TITLE
telegram 开启前 报错

### ISSUE THREAD

**Issue by lbcake** [SpriteOvO/Telegram-Anti-Revoke#44]
![Snipaste_2021-01-30_12-03-43](https://user-images.githubusercontent.com/26319880/106346813-bf8a8280-62f4-11eb-86fb-ed42ece69e7e.png)

开启tg 报此错误  

请麻烦看下是什么情况  
win 64
使用版本 23 Dec 2020

**Comment by SpriteOvO** [comment]
无法用 插件 3.0 版 在 TG 2.5.8 x86 版上复现该问题，您使用的是哪个版本的插件？

**Comment by lbcake** [comment]
> 无法用 插件 3.0 版 在 TG 2.5.8 x86 版上复现该问题，您使用的是哪个版本的 插件 和 TG ？

![20210131164638](https://user-images.githubusercontent.com/26319880/106379012-ef648380-63e3-11eb-9dfb-395b48f95755.jpg)
![image](https://user-images.githubusercontent.com/26319880/106379017-f7242800-63e3-11eb-996f-6f2162475d00.png)


你说的  2.58         x86版是什么版本？

**Comment by SpriteOvO** [comment]
> 你说的 2.58 x86版是什么版本？

2.5.8 是指 `Telegram.exe` 的版本号，你可以对 `Telegram.exe` 文件 右键 -> 属性 -> 详细信息 然后截图看看

**Comment by lbcake** [comment]
> > 你说的 2.58 x86版是什么版本？
> 
> 2.5.8 是指 `Telegram.exe` 的版本号，你可以对 `Telegram.exe` 文件 右键 -> 属性 -> 详细信息 然后截图看看

![image](https://user-images.githubusercontent.com/26319880/106379261-a281ac80-63e5-11eb-8e04-304b5c441ddc.png)

**Comment by SpriteOvO** [comment]
hmmm，可能是插件对旧版本的 Telegram 兼容有点问题（我测试的是最早到 2.4.0 都是可用的
一个解决方法是升级 Telegram 到最新版本，具体方法：在 Telegram 中点击 设置 -> 高级 -> 检查更新

**Comment by lbcake** [comment]
> hmmm，可能是插件对旧版本的 Telegram 兼容有点问题（我之前测试的是最早到 2.4.0 都是可用的，可能漏掉 2.4.7 版本的测试了
> 一个解决方法是升级 Telegram 到最新版本，具体步骤：在 Telegram 中点击 设置 -> 高级 -> 检查更新

2.58   和2.47 都是什么东西？ 还有后边说哦x86   32位系统还是什么？  麻烦解答下

我的tg 检查更新 已经说是最新版本了  我不知道怎么会出来俩版本号

**Comment by SpriteOvO** [comment]
> 2.58 和2.47 都是什么东西？ 还有后边说哦x86 32位系统还是什么？ 麻烦解答下

2.5.8 是目前 Telegram 桌面端的最新版本（[GitHub 发布页](https://github.com/telegramdesktop/tdesktop/releases/tag/v2.5.8)）
从你上面的截图来看，您正在使用 2.4.7 的旧版本。

x86 是指 Telegram 的版本平台，Telegram 在最近首次释出了 x64 的版本，该版本可以在 x64 的 Windows 系统中使用以获得更好的性能提升和更多的内存空间，在这之前 Telegram 只有 x86 版本。

> 我的tg 检查更新 已经说是最新版本了 我不知道怎么会出来俩版本号

在 Telegram 更新页面，显示的版本号是多少呢？方便截图一下吗？

下图是我自己的截图，使用的是最新 2.5.8 版本：
![image](https://user-images.githubusercontent.com/33660554/106379784-56d10200-63e9-11eb-80d8-d56331414c42.png)

**Comment by lbcake** [comment]
> > 2.58 和2.47 都是什么东西？ 还有后边说哦x86 32位系统还是什么？ 麻烦解答下
> 
> 2.5.8 是目前 Telegram 桌面端的最新版本（[GitHub 发布页](https://github.com/telegramdesktop/tdesktop/releases/tag/v2.5.8)）
> 从你上面的截图来看，您正在使用 2.4.7 的旧版本。
> 
> x86 是指 Telegram 的版本目标平台，Telegram 在最近首次释出了 x64 的版本，该版本可以在 x64 的 Windows 系统中使用以获得更好的性能提升和更多的内存空间，在这之前 Telegram 只有 x86 版本。
> 
> > 我的tg 检查更新 已经说是最新版本了 我不知道怎么会出来俩版本号
> 
> 在 Telegram 更新页面，显示的版本号是多少呢？方便截图一下吗？
> 
> 如下是我自己的截图，使用的是最新 2.5.8 版本：
> ![image](https://user-images.githubusercontent.com/33660554/106379784-56d10200-63e9-11eb-80d8-d56331414c42.png)

![image](https://user-images.githubusercontent.com/26319880/106381477-eb406200-63f3-11eb-93a6-ae62c0423345.png)
是这样的 我电脑里有装了两个TG   刚才弄混了

以上截图 对应我使用的tg 出问题也是在这个基础上  并不是每次都会报错  我这里也不知道什么原因.有时候打开没事  有时候报错（至于另一版2.47的 打开较少 所以没怎么更新  但是我记得有一次打开 出现了一次上边报错的情况）

**Comment by SpriteOvO** [comment]
那现在还会报错吗，不报错的话我就先关闭这个 issue 了。
下次再报错可以附上 ArLog.txt（插件日志文件）的内容，方便排查问题。

**Comment by lbcake** [comment]
> 那现在还会报错吗，不会的话我就先关闭这个 issue 了。
> 下次再报错可以附上 ArLog.txt（插件日志文件）的内容，方便排查问题。

好的  在报错 下次给你贴上 ArLog    感谢解答

**Comment by SpriteOvO** [comment]
该问题已确认是一个 BUG，并应该在刚刚发布的 [0.3.1](https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases/tag/0.3.1) 版本中修复，感谢您的反馈！
