### ISSUE TITLE
[Question] Plugin does not work for Telegram x64 version?

### ISSUE THREAD

**Issue by 0x11DFE** [SpriteOvO/Telegram-Anti-Revoke#46]
I'm running on version 2.5.9 x64

**Comment by SpriteOvO** [comment]
This plugin currently only works with the Telegram x86 version, for x64 we are sure to support it in the future, but the workload is bigger so it will take some time.

A suggestion is to switch Telegram back to the x86 version and then when the plugin supports x64, all users will receive an update notification in the plugin.

**Comment by SpriteOvO** [comment]
@0x11DFE Hey! Sorry I know this is a little late. I just completed the x64 compatibility work, could you help test it?
You can download the artifact compiled by CI for testing on [that commit's GitHub Actions Summary page](https://github.com/SpriteOvO/Telegram-Anti-Revoke/actions/runs/961892880) (click on `Win*-x64-Release`).

**Comment by 0x11DFE** [comment]
> @0x11DFE Hey! Sorry I know this is a little late. I just completed the x64 compatibility work, could you help test it?
> 
> You can download the artifact compiled by CI for testing on [the latest commit's GitHub Actions Summary page](https://github.com/SpriteOvO/Telegram-Anti-Revoke/actions/runs/961892880) (click on `Win*-x64-Release`).

Tried both the Win7 & Win10 x64 and both are crashing on the version 2.7.4 x64 of Telegram.

**Comment by SpriteOvO** [comment]
@0x11DFE Oh, I forgot about this, that was working on 2.7.9, I'll do some forward compatibility later. Thanks for your testing.

**Comment by SpriteOvO** [comment]
@0x11DFE I can't repro it. What is the timing of the crash that occurs? After launch? Messages revoked?

**Comment by 0x11DFE** [comment]
> @0x11DFE I can't repro it. What is the timing of the crash that occurs? After launch? messages deleted? or something else?

The crash occurs when Telegram gets executed.

**Comment by 0x11DFE** [comment]
While debugging the application is throwing an exception at VERSION!VerQueryValueW

**Comment by SpriteOvO** [comment]
@0x11DFE Thanks! I made an attempt, could you try this commit? If the crash still happens, please let me know if it happens inside the Win32 API or in the detour function of the plugin. Maybe a screenshot would be more helpful. :-)

**Comment by 0x11DFE** [comment]
> @0x11DFE Thanks! I made an attempt, could you try [this commit](https://github.com/SpriteOvO/Telegram-Anti-Revoke/actions/runs/963084143)? If the crash still happens, please let me know the exception code and if it happens inside the Win32 API or in the detour function of the plugin (they have the same function name). Maybe a screenshot would be more helpful. :-)

No crash works perfectly !

**Comment by zloishax** [comment]
for telegram version 2.8.4 x64 does not work

**Comment by SpriteOvO** [comment]
> for telegram version 2.8.4 x64 does not work

@zloishax Some improvements are being made and will be released soon

**Comment by zloishax** [comment]
my laptop is x64

> > for telegram version 2.8.4 x64 does not work
> 
> @zloishax Some improvements are being made and will be released soon. Please use the x86 version for now.

my laptop is x64

**Comment by SpriteOvO** [comment]
> > > for telegram version 2.8.4 x64 does not work
> > 
> > 
> > @zloishax Some improvements are being made and will be released soon. Please use the x86 version for now.
> 
> my laptop is x64

x64 OS can run x86 programs, they are compatible

**Comment by zloishax** [comment]
> > my laptop is x64
> 
> @zloishax x64 OS can run x86 programs, they are compatible

It turned out on the x86 version

**Comment by SpriteOvO** [comment]
New version [0.4.0](https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases/tag/0.4.0) has been released.
