### ISSUE TITLE
[Question] 做这个项目的初衷是什么？它与TG隐私聊天的需求是相违背的吧

### ISSUE THREAD

**Issue by ameaninglessname** [SpriteOvO/Telegram-Anti-Revoke#47]

**Comment by SpriteOvO** [comment]
初衷是尝试编写将其他聊天软件的防撤回思路适用到 TG 的概念证明，并借此巩固自己的逆向知识和学习 TG 的开源代码。
即使该项目没有开源或发布，该问题及思路依然是客观存在的，如果其能够促使 TG 缓解此类问题是我们更希望看到的结果。

感谢您的提问！

**Comment by ameaninglessname** [comment]
那你有在bugs.telegram.org提个建议么

**Comment by SpriteOvO** [comment]
> [那你有去这里提个功能建议么](https://bugs.telegram.org/)

没有，一方面是因为这个社区出现的时间比该项目晚，所以就没想起来去提这个问题，另一方面是因为我自己目前对缓解建议也没什么头绪。
