### ISSUE TITLE
hi. how i can in Portable Version?

### ISSUE THREAD

**Issue by hreza137575** [SpriteOvO/Telegram-Anti-Revoke#48]
how i can in Portable Version? where is date folder in portable version?

**Comment by SpriteOvO** [comment]
The usage is clearly described in the README:

> 1. Go to the [Release Page](https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases) to download the latest version of the plugin.  
> 2. Close the running Telegram process.  
> 3. Copy *version.dll* file into the Telegram root directory.  
> 4. Run the Telegram program.

Which works for both the installation version and portable version.

The root directory of the portable version is the directory of `Telegram.exe`.

**Comment by timea-techgirl** [comment]
@SpriteOvO It is no longer working since v0.3.1
It seems that the dll is not being loaded at all because there is no log created and the version.dll file can be deleted while telegram is open.
