### ISSUE TITLE
[Bug report]  在使用非官方客户端时遭遇错误

### ISSUE THREAD

**Issue by Leisuredpootle** [SpriteOvO/Telegram-Anti-Revoke#51]
### Describe the bug
在消息被删除时会弹出一个错误,且无法阻止删除
使用的是非官方客户端,项目地址: https://github.com/TDesktop-x64/tdesktop

### Steps to reproduce
1. 在群组内发送“Test”
2. 使用Android端删除“Test”

### Expected behaviour
消息删除成功被拦截

### Actual behaviour
弹出错误,且消息删除未被拦截

### Configuration
* Operating system: Windows 10 LSTC
* Version of Telegram: 2.6.1.1

[ArLog.txt](https://github.com/SpriteOvO/Telegram-Anti-Revoke/files/6063035/ArLog.txt)

**Comment by SpriteOvO** [comment]
考虑到更新复杂度问题，插件目前不支持除官方以外的版本，建议切换回官方版本使用。
感谢您的报告！

**Comment by Leisuredpootle** [comment]
> 考虑到更新复杂度问题，插件目前不支持除官方以外的版本，建议切换回官方版本使用。
> 感谢您的报告！

好的,谢谢您的回复

**Comment by Rongronggg9** [comment]
文中的这个客户端[为了 fontmod 特别放行了 winmm.dll 的加载](https://github.com/TDesktop-x64/tdesktop/commit/31d6730c1e58c710e1cb3196c58ae468ce8e2a58)，是否可以考虑添加对这个客户端的支持呢？

BTW，fontmod 不是修改 Telegram 字体所必需的，可以使用注册表重映射 Telegram 使用的字体，因此可以使修改字体与防撤回共存。
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes]
; 替换 Open Sans 对大部分使用者没有太大影响
"DAOpenSansRegular"="Sarasa Gothic TC"                    ; 常规体
"DAOpenSansRegularItalic"="Sarasa Gothic TC Italic"       ; 斜体
"DAOpenSansSemibold"="Sarasa Gothic TC Bold"              ; 粗体
"DAOpenSansSemiboldItalic"="Sarasa Gothic TC Bold Italic" ; 粗斜体
; 不要用非等宽字体替换 Consolas；Consolas 是系统自带字体，小心替换
"Consolas"="Sarasa Term TC"                               ; 等宽字体
```
