### ISSUE TITLE
Not working on Telegram Desktop v2.7.1

### ISSUE THREAD

**Issue by venusbahar** [SpriteOvO/Telegram-Anti-Revoke#57]
I just installed on my Telegram Desktop v2.7.1 on Windows 10.
When the other-side user delete the message, on my Telegram the message won't be deleted. But it will be converted to something like this:
`b994278f-bea9-4b4c-977a-89d10d92ea62`
Also, the "deleted" label not appear on the deleted message.

**Comment by SpriteOvO** [comment]
idk what that string is, it should not be caused by plugin.
Could you check if there is a `ArLog.txt`  file is generated in the plugin directory and post its content here?

**Comment by venusbahar** [comment]
> idk what that string is, it should not be caused by plugin.
> Could you check if there is a `ArLog.txt` file is generated in the plugin directory and post its content here?

It was just an English word.
I checked, the ArLog.txt file is not in the plugin directory and the file `Version.dll` has been removed from Telegram directory by itself (Antivirus did not this).
Also Anti-Revoke not function anymore, I guess I should reinstall it.

**Comment by SpriteOvO** [comment]
> and the file `Version.dll` has been removed from Telegram directory by itself

The plugin doesn't remove itself, I believe it disappears due to other factors.

**Comment by VeryBigGod** [comment]
Did you just installed the x64 version?
It can only run on x86 version for now.
