### ISSUE TITLE
[Bug report] 最新版本1.9.21已不兼容

### ISSUE THREAD

**Issue by ECIAP** [SpriteOvO/Telegram-Anti-Revoke#6]
### Describe the bug
与 https://github.com/SpriteOvO/Telegram-Anti-Revoke/issues/5 产生的错误一致
### Steps to reproduce
1. 打开最新电报
2. 
3. 

### Expected behaviour
正常工作

### Actual behaviour
电报奔溃 点击忽略后仍可运行电报

### Configuration
* Operating system:  Windows 10
* Version of Telegram:  1.9.21

<details><summary><b>Logs</b></summary>
Anti-Revoke Plugin
An error has occurred!
Please help us fix this problem.
SearchSigns() failed.

Click "Abort" or "Ignore" will pop up GitHub issue tracker page.
You can submit this problem to us there.
Thank you very much.
中止(A) 重试(R) 忽略(I)
</details>

**Comment by SpriteOvO** [comment]
已更新 v0.1.5 版本。
