### ISSUE TITLE
[Bug report] 装了插件后无法取消置顶信息 Can't cancel the top message after installing the plugin

### ISSUE THREAD

**Issue by MLC1158** [SpriteOvO/Telegram-Anti-Revoke#60]
### Describe the bug
无法取消置顶(取消置顶不成功)
Unable to cancel the top (unsuccessful in canceling the top)
### Steps to reproduce
1. 点击取消置顶
Click to un-top
2. 自己的电脑上已经显示取消
The cancellation has been shown on your own computer
3. 但是实际却没有取消成功
But the actual cancellation was not successful

### Expected behaviour
能成功取消置顶
Can successfully cancel
### Actual behaviour
但是在别人的Telegram还显示着置顶消息
But in other people's Telegram is still showing top messages
### Configuration
* Operating system: Windows 10 专业版(Professional) x64 20H2
* Version of Telegram: 2.7.4
* Version of the plugin: 0.3.2

<details><summary><b>Logs</b></summary>
Insert the content of ArLog.txt here. (if necessary)<br>
(The log file is in the same directory with version.dll file)
</details>

**Comment by SpriteOvO** [comment]
![image](https://user-images.githubusercontent.com/33660554/116972681-f5714580-aced-11eb-9d29-577c3e2e6e08.png)

无法复现
