### ISSUE TITLE
for telegram version 2.8.4 x64 does not work [Bug report] 

### ISSUE THREAD

**Issue by zloishax** [SpriteOvO/Telegram-Anti-Revoke#62]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
* Operating system: 
* Version of Telegram: 
* Version of the plugin: 

<details><summary><b>Logs</b></summary>
Insert the content of ArLog.txt here. (if necessary)<br>
(The log file is in the same directory with version.dll file)
</details>

**Comment by zloishax** [comment]
win 10

**Comment by SpriteOvO** [comment]
Duplicate of #46
