### ISSUE TITLE
[Feature Request] Argument support for Launcher

### ISSUE THREAD

**Issue by 0x11DFE** [SpriteOvO/Telegram-Anti-Revoke#65]
An option to add arguments on the process creation [`CreateProcessA`](https://github.com/SpriteOvO/Telegram-Anti-Revoke/blob/d37790b13650b5055431160e724d2c04dc70fce5/Source/Launcher/Main.cpp#L170) could be useful in some scenarios example if we want to start Telegram minimized the argument would be `-autostart`.

**Comment by SpriteOvO** [comment]
Committed changes to support forwarding command line arguments, but simply passing `-autorun` to Telegram.exe does not minimize it at startup, and I have a hunch that the feature will require decrypting and modifying configuration data, so the feature may be abandoned as too difficult to implement.

**Comment by 0x11DFE** [comment]
> Committed changes to support forwarding command line arguments, but simply passing `-autorun` to Telegram.exe does not minimize it at startup, and I have a hunch that the feature will require decrypting and modifying configuration data, so the feature may be abandoned as too difficult to implement.

I did some testing and `-autostart` actually works but it is required to enable autostart from within Telegram's settings.
So after placing the shortcut to `shell:startup` we need to move to Telegram's advanced settings and tick **Launch Telegram when system starts** and **Launch minimized** after that close Telegram entirely.

Move back to `shell:startup` and delete the Telegram's official shortcut and modifying our own shortcut by going to the file properties and **Target** adding `-autostart` at the end of the path.
Now the application will start as minimized everytime the system starts.

**Comment by 0x11DFE** [comment]
Now that we know that, How does Telegram restrict the action of using `-autostart` ?
Well after looking at the process events on enabling **Launch minimized** it seems that Telegram query and modify a file called `settingss` which is located at `%APPDATA%\Telegram Desktop\tdata\settings` and might be encrypted.
![Telegram events on autostart](https://user-images.githubusercontent.com/43712252/127769348-aa371cfe-c845-4577-a11c-91696d0e4e88.png)

**Comment by SpriteOvO** [comment]
@0x11DFE If we delete the Telegram shortcut, won't it automatically disable the auto-run option? If so, this is an effective and simple solution. :+1:

**Comment by 0x11DFE** [comment]
> @0x11DFE If we delete the Telegram shortcut, won't it automatically disable the auto-run option? If so, this is an effective and simple solution. 👍

No it doesn't disable the option 😋

**Comment by SpriteOvO** [comment]
Released [v0.4.1](https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases/tag/0.4.1).
Thanks for your report and test！
