### ISSUE TITLE
无法多开 TG

### ISSUE THREAD

**Issue by geyeliangcha** [SpriteOvO/Telegram-Anti-Revoke#67]
无法多开

**Comment by SpriteOvO** [comment]
将插件分别放入你要多开的 Telegram 文件夹并从 Launcher 启动
多开的开机自启也需要分别复制每个 Telegram 目录中的 Launcher 的快捷方式到 startup 目录
以上方式针对较新的 Telegram 版本，旧版本只需放入 dll 并重命名为 version.dll 即可，具体请阅读 release 中的 README.md 文件
