### ISSUE TITLE
[Feature Request] 希望能增加对windows server系统的支持 Hope to directly support the windows server system

### ISSUE THREAD

**Issue by a12110** [SpriteOvO/Telegram-Anti-Revoke#68]
我在Windows server2012系统上使用0.4.0版本的exe版本启动时提示错误"Resource files are missing.
Did you forget to copy the "TAR-Resources"folder?"
希望能增加对server系统的支持，谢谢。
I use the 0.4.0 version of the exe version to start on the Windows server2012 system and the error "Resource files are missing.
Did you forget to copy the "TAR-Resources"folder?"
Hope to increase support for the server system.

**Comment by SpriteOvO** [comment]
请问文件夹 TAR-Resources 实际复制到 Telegram 目录了吗？如果操作没有错误，我会在晚些时候安装一个 Server 2012 操作系统进行测试。

Has the folder TAR-Resources actually been copied to the Telegram directory? If there are no mistakes, I will install a Server 2012 OS to test it later.

**Comment by a12110** [comment]
没复制完全
😅
