### ISSUE TITLE
[Bug report] At Telegram version 2.9, "deleted" tag cannot be shown

### ISSUE THREAD

**Issue by DullJZ** [SpriteOvO/Telegram-Anti-Revoke#69]
### Describe the bug
At Telegram version 2.9, "deleted" tag cannot be shown.
在版本2.9的Telegram 中，“已删除”标签无法显示。
### Steps to reproduce
The other party deletes messages during group chat
群组聊天过程中对方删除消息
### Expected behaviour
Expected to be shown.
应当显示
### Actual behaviour
The deleted message is retained, but no "deleted" label appears
被删除的信息保留下来了，但无“已删除”标签出现
### Configuration
* Operating system: Windows 10 x64
* Version of Telegram: Telegram 2.9 x86 便携版
* Version of the plugin: v0.4.0

**Comment by SpriteOvO** [comment]
Thanks for reporting!
Fixed in [v0.4.1](https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases/tag/0.4.1)(a3f3e61).
