### ISSUE TITLE
[Feature Request] Download images as they are delivered

### ISSUE THREAD

**Issue by Numenorean** [SpriteOvO/Telegram-Anti-Revoke#77]
### Is your feature request related to a problem? Please describe.
When the message is an image and i don't check telegram before to load it - telegram stacks on trying to load it

### Describe the solution you'd like
Download as minumum all the images as they are delivered in cache

### Additional context
gif how it is right now
![](https://i.imgur.com/svrEmQH.gif)

**Comment by SpriteOvO** [comment]
Sometimes when an image is deleted, the `file_id` (maybe) of that image will no longer be available. And the caching logic is controlled by Telegram. If caching all images in all chats would consume a lot of memory, this is not a good idea. There is currently no way to fix it, though it is certainly an problem.

Thanks for reporting!
