### ISSUE TITLE
[Bug report] Incorrect work of the plugin with the TG 3.1.7 (beta)

### ISSUE THREAD

**Issue by yuruyu6** [SpriteOvO/Telegram-Anti-Revoke#78]
Plugin does not work correctly with latest Telegram version 3.1.7 (beta)
The error appears when opening any chat

![image](https://user-images.githubusercontent.com/38044657/136435687-fae9988f-09c3-4299-a7d4-0fb57d3ba935.png)
### Configuration
* Operating system: Windows 11 22471.1000
* Version of Telegram: 3.1.7 (beta)
* Version of the plugin: 0.4.1

**Comment by K2M74** [comment]
> Yes, the plugin needs to be updated, for now you can use the Telegram x64 version which works fine, I will release a new version later to fix the error on x86.

我这3.1.8，64位也报错了。

**Comment by SpriteOvO** [comment]
Fixes are released in the new version [v0.4.2](https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases/tag/0.4.2).
