### ISSUE TITLE
[Bug report] InitDynamicData_EditedIndex() failed.

### ISSUE THREAD

**Issue by charlieqwq** [SpriteOvO/Telegram-Anti-Revoke#79]
### Describe the bug
Program crashed when started
InitDynamicData_EditedIndex() failed.

### Steps to reproduce
Just run it and wait for a few second

### Configuration
* Operating system: windows 10 21H1
* Version of Telegram: 3.1.8 x64
* Version of the plugin: 0.4.1

<details><summary><b>Logs</b></summary>
[ArLog.txt](https://github.com/SpriteOvO/Telegram-Anti-Revoke/files/7311986/ArLog.txt)
</details>

**Comment by veratone** [comment]
This bug appeared when I enabled "Driver Signature Enforcement Test Signing Mode" I believe.

**Comment by foxdodo** [comment]
这意思每次tg更新作者都要跟进了?

**Comment by EmileIssarov** [comment]
Same
![image](https://user-images.githubusercontent.com/92203995/136649259-a2a579df-4056-4011-b18e-79e6fe828d07.png)

**Comment by SpriteOvO** [comment]
Fixes are released in the new version [v0.4.2](https://github.com/SpriteOvO/Telegram-Anti-Revoke/releases/tag/0.4.2).
