### ISSUE TITLE
An error has occurred

### ISSUE THREAD

**Issue by faraji1452** [SpriteOvO/Telegram-Anti-Revoke#80]
### Steps to reproduce
1. 
![Screenshot 2021-10-08 205928](https://user-images.githubusercontent.com/92178161/136598522-48583ad3-9c39-4e19-866a-f1385e8c8b99.png)

2. An error has occurred
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
* Operating system: windows 10 64 bit - corei5 8th - ram 8 GB - GPU MX110 - HDD 1 TB
* Version of Telegram: Telegram Beta 3.1.8 x64
* Version of the plugin: 0.4.1

<details><summary><b>Logs</b></summary>
Insert the content of ArLog.txt here. (if necessary)<br>
(The log file is in the same directory with version.dll file)
</details>

**Comment by GenyaWhite** [comment]
Let me know if you solved the issue
