### ISSUE TITLE
[Feature Request] Hide sponsored messages

### ISSUE THREAD

**Issue by Neurotoxin001** [SpriteOvO/Telegram-Anti-Revoke#86]
### Is your feature request related to a problem? Please describe.
Problem is sponsored messages by telegram in public channels.

### Describe the solution you'd like
Create another repo or add this patch:
https://github.com/msva/mva-overlay/blob/master/net-im/telegram-desktop/files/patches/0/conditional/hide-sponsored-messages/0000-history_history.cpp.patch
To current repo to the same dll/exe.

### Additional context
You can also add this patch:
https://github.com/ilya-fedin/kotatogramAUR/blob/master/kotatogram-desktop/0001-Add-an-option-to-hide-messages-from-blocked-users-in.patch
It's adds an option to hide messages from blocked users in groups. It's usefull too.

upd:
patch from first link is not working. This is working:
```
diff --git a/Telegram/SourceFiles/data/data_sponsored_messages.cpp b/Telegram/SourceFiles/data/data_sponsored_messages.cpp
index 1dc5b49..91cba9c 100644
--- a/Telegram/SourceFiles/data/data_sponsored_messages.cpp
+++ b/Telegram/SourceFiles/data/data_sponsored_messages.cpp
@@ -93,7 +93,7 @@ bool SponsoredMessages::append(not_null<History*> history) {
 }
 
 bool SponsoredMessages::canHaveFor(not_null<History*> history) const {
-	return history->isChannel();
+	return false;
 }
 
 void SponsoredMessages::request(not_null<History*> history) {

```

**Comment by SpriteOvO** [comment]
Thanks for your submit.

I don't intend to develop a feature to hide sponsored messages, Telegram has already given too much as a free software, and I believe it will not show very annoying type of sponsored messages, which is acceptable to me.

The feature you mentioned "hide messages from blocked users", it is very useful and I like it a lot. But as a binary patch plugin, it is difficult to fully implement all the details in the patch you give. Eventually I may implement a switch as an option in the config file, hiding messages from blocked users when it is enabled. I will take a look at it when I have time, but there is no guarantee, as that feature is not the main purpose of this project.

**Comment by SpriteOvO** [comment]
Close since the feature in the title will not be implemented. You can open a new issue to track the progress of the "hide messages from blocked users" feature if you wish.
