### ISSUE TITLE
[Bug report]  2.1版本功能疑似失效...

### ISSUE THREAD

**Issue by ECIAP** [SpriteOvO/Telegram-Anti-Revoke#9]
### Describe the bug
无法防撤回了 , 消息依然会被删除 
### Steps to reproduce
1. A发一条消息
2. A删除一条消息
3. B处消息消失

### Expected behaviour
Tell us what should happen
消息应该不被撤回

### Actual behaviour
Tell us what happens instead
群组里的消息被撤回了

### Configuration
* Operating system: Win 10 
* Version of Telegram:  v2.1

<details><summary><b>Logs</b></summary>
Insert ArLog.txt here. (if necessary)<br>
It's in the same directory as the avrt.dll file.
</details>

**Comment by SpriteOvO** [comment]
我这边一切正常，请检查 Telegram 根目录是否存在 version.dll 文件和 Arlog.txt 日志文件。
如果问题依旧存在，请上传 Arlog.txt 中的近期日志内容。

**Comment by ECIAP** [comment]
! 十分抱歉 好像是不小心误删version.dll 了
